apiVersion: v1
kind: Service
metadata:
  name: llm-inference-qwen-service
  namespace: cse239fall2025
spec:
  type: ClusterIP
  selector:
    app: llm-inference-qwen
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llm-inference-qwen-ingress
  namespace: cse239fall2025
  annotations:
    kubernetes.io/ingress.class: haproxy
spec:
  rules:
  - host: llm-qwen-sshar134.nrp-nautilus.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: llm-inference-qwen-service
            port:
              number: 80
